//#This file is developed by Team 52 of COMP90024 of The University of Melbourne.
//#Researched cities : All the cities in Melbourne region
//#Team member - id
//#Nitish Mathur  				954892     
//#Yash Shinde     				920691
//#Nakia Silva  					796504
//#Shreyas Walvekar    				961621
//#Krishna Srinivas Sundararajan  		977863


# Set proxies
- name: Set Proxies
  lineinfile:
    path: '/etc/environment'
    line: "{{ item }}"
  with_items:
    - 'http_proxy="http://wwwproxy.unimelb.edu.au:8000"'
    - 'https_proxy="http://wwwproxy.unimelb.edu.au:8000"'
    - 'ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"'
    - 'no_proxy=localhost,127.0.0.1,127.0.1.1,ubuntu,{{ansible_eth0.ipv4.address}}'

- debug:
    msg: "{{ansible_eth0.ipv4.address}}"






