#This file is developed by Team 52 of COMP90024 of The University of Melbourne.
#Researched cities : All the cities in Melbourne region
#Team member - id
#Nitish Mathur  				954892     
#Yash Shinde     				920691
#Nakia Silva  					796504
#Shreyas Walvekar    				961621
#Krishna Srinivas Sundararajan  		977863
---
# Create volumes snapshot(s)
- name: Create volume snapshot(s)
  os_volume_snapshot:
    state: present
    volume: '{{ item.vol_name }}'
    display_name: "{{ item.vol_name }}-{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"
    wait: yes
    timeout: 600
    force: yes
    availability_zone: '{{ availability_zone }}'
  loop: '{{ volumes }}'
